name: Deploy to staging
on:
  push:
    branches: [main]

jobs:
  redeploy_everything:
    runs-on: ubuntu-latest
    name: Deploying everything to staging cluster

    steps:
      - name: SSH into server
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" &> ~/ssh_key
          mkdir -p ~/.ssh
          echo "${{ secrets.KNOWN_HOSTS }}" &> ~/.ssh/known_hosts
          chmod 700 ~/ssh_key
          ssh -i ~/ssh_key ubuntu@65.2.82.128 -t "cd devops-deploy/ && git pull && pnpm install && pnpm run build && pm2 restart all"
